name: tdd_post
description: A new First TDD project

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # test
  mockito: ^5.3.2

  # Service locator
  get_it: ^7.2.0

  # Bloc for state management
  flutter_bloc: ^8.1.1

  # Value equality
  equatable: ^2.0.5

  # Functional programming thingies
  dartz: ^0.10.1

  # Remote API
  data_connection_checker_nulls: ^0.0.2
  http: ^0.13.5

  # Local cache
  shared_preferences: ^2.0.15
  flutter_slidable: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # for generate class
  build_runner: ^2.2.1

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
